import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { CATEGORIES } from '@/lib/archetypes'
import { submitRequest } from './actions'

export default async function RequestPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login?next=/request')
  }

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-2xl font-bold">Request New Content</h1>
        <p className="text-zinc-400 text-sm mt-1">
          Add a movie, book, historical event, or story to the library
        </p>
      </header>

      <form action={submitRequest} className="space-y-4">
        <div>
          <label htmlFor="title" className="block text-sm font-medium text-zinc-300 mb-1">
            Title
          </label>
          <input
            id="title"
            name="title"
            type="text"
            required
            placeholder="e.g., The Godfather, Marcus Aurelius, Noah's Ark"
            className="w-full bg-zinc-900 border border-zinc-800 rounded-xl px-4 py-3 text-white placeholder-zinc-500 focus:outline-none focus:ring-2 focus:ring-amber-500"
          />
        </div>

        <div>
          <label htmlFor="category" className="block text-sm font-medium text-zinc-300 mb-1">
            Category
          </label>
          <select
            id="category"
            name="category"
            required
            className="w-full bg-zinc-900 border border-zinc-800 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-amber-500"
          >
            {Object.entries(CATEGORIES).map(([key, value]) => (
              <option key={key} value={key}>
                {value.icon} {value.name}
              </option>
            ))}
          </select>
        </div>

        <button
          type="submit"
          className="w-full bg-amber-600 hover:bg-amber-500 text-white font-medium py-4 rounded-xl transition-colors"
        >
          Generate Characters
        </button>
      </form>

      <p className="text-center text-xs text-zinc-500">
        Character analysis will be generated by AI and added to the public library.
        This may take 30-60 seconds.
      </p>
    </div>
  )
}
